### ISSUE TITLE
API for authencation 

### ISSUE THREAD

**Issue by baotnq** [easywebhub/BackendEasyWeb#2]
#### Notes: @thinnv @nemesisqp  split  website.json out of account.json and referenced by websiteId, view https://gist.github.com/baotnq/5c97a47a200784678d5057017feaa96a

Reference from https://github.com/easywebhub/easyapp/issues/74, @thinnv re-write API using create wiki [here](https://github.com/easywebhub/BackendEasyWeb/wiki/_new)
### Authentication (with sample  `input & output json`)
- Sign Up  
- Sign In 
- Update Account Info
### Create new website
- new website with owner is current user `["creator", "dev"]`
- add `websiteId` to list of websites
### Allow users to access website
- update website.json with input:  `websiteId` and  permisson `accessLevel`
- add `websiteId` to list of websites
### Update website Info:
- update Stagging or Deploy information
- update website.json only.
### List of results (json) for easy debug or integrate with Aurelia Admin
- List of accounts
- List of created websites 

@thinnv  modify the code and give clear samples for @nemesisqp and @tungptvn

**Comment by baotnq** [comment]
@thinnv  bao giờ cung cấp được các API này cho @nemesisqp  vậy

**Comment by thinnv** [comment]
Qua lễ 2/9 nha a

**Comment by thinnv** [comment]
- Sign Up:  api http://api.easywebhub.com/api-user/InsertUser

```
    Json: 
    {
  "accountType": "user",
  "userName": "baotnq",
  "password": "123456",
  "status": "verified",
  "info": {
    "name": "Trịnh Ngọc Quốc Bảo",
    "age": 31,
    "sex": "nam",
    "address": ""
  },
  "websites": [
    {
      "accounts": [
        {
          "accessLevel": [
            "creator",
            "admin"
          ]
        }
      ],
      "name": "website-easy",
      "displayName": "Website of easywebhub",
      "accessLevel": [
        "creator",
        "admin"
      ],
      "url": "http://easywebhub.com",
      "stagging": [
        {
          "name": "Github Environment",
          "hostingFee": "free",
          "url": "https://easywebhub.github.io/easy-websites",
          "git": "https://github.com/easywebhub/easy-websites.git"
        }
      ],
      "production": [
        {
          "name": "Github Environment",
          "hostingFee": "free",
          "url": "https://easywebhub.github.io/easy-websites",
          "git": "https://github.com/easywebhub/easy-websites.git"
        },
        {
          "name": "EasyWeb Environment",
          "hosting-fee": "basic",
          "url": "https://easy-web.easywebhub.com",
          "git": "https://git.easywebhub.com/easy-websites.git"
        }
      ]
    }
  ]
}
```
- Sign In : Như cũ
- Update Account Info : http://api.easywebhub.com/api-user/UpdateUser
- Create new website: http://api.easywebhub.com/api-user/CreateWebsite
  --> tham khảo cấu trúc insertOrder
- List of accounts: http://api.easywebhub.com/api-user/GetListUser
- List of created websites:  http://api.easywebhub.com/api-user/GetListWebsite
  @nemesisqp  a check nha

**Comment by thinnv** [comment]
GetListWebsite
https://gist.github.com/thinnv/47d4d486aa642c976c2f3f28c9b9d649

**Comment by thinnv** [comment]
GetListUser
https://gist.github.com/thinnv/0f909b0914fa3c618f7ffba68660494b

**Comment by nemesisqp** [comment]
gọi UpdateUser mất account

create user POST http://api.easywebhub.com/api-user/InsertUser
data

```
{
    "username": "666",
    "password": "666",
    "accountType": "user",
    "websites": []
}
```

result

```
{
    "Result": true,
    "Message": "Thành công!",
    "StatusCode": 200,
    "ItemsCount": 1,
    "Data": true
}
```

logon POST  http://api.easywebhub.com//api-user/logon
data

```
{
    "username": "666",
    "password": "666"
}
```

result

```
{
  "Result": true,
  "Message": "Thành công!",
  "StatusCode": 200,
  "ItemsCount": 1,
  "Data": {
    "AccountId": "899e1ac4-ac26-4207-b49f-167c7862f3d1",
    "AccountType": "user",
    "UserName": "666",
    "Password": "Mo/GoWzePT4Z5CUis3zW+PwqziNJHTPDcITesEr5BF8=",
    "PasswordSalt": "uZl6rzOQYmvYnUfD2moudfGjiQUWZDZ0",
    "Status": null,
    "Info": null,
    "Websites": []
  }
}
```

check user co ton tai GET http://api.easywebhub.com/api-user/GetListUser
có

```
 {
      "AccountId": "899e1ac4-ac26-4207-b49f-167c7862f3d1",
      "AccountType": "user",
      "UserName": "666",
      "Password": "Mo/GoWzePT4Z5CUis3zW+PwqziNJHTPDcITesEr5BF8=",
      "PasswordSalt": "uZl6rzOQYmvYnUfD2moudfGjiQUWZDZ0",
      "Status": null,
      "Info": null,
      "Websites": []
    },
```

call update user POST http://api.easywebhub.com/api-user/UpdateUser
data

```
{
    "AccountId": "899e1ac4-ac26-4207-b49f-167c7862f3d1",
    "password": "666",
    "websites": [
        {
            "name": "website-easy 333",
            "displayName": "Website of 3333"
        }
    ]
}
```

result

```
{
  "Result": true,
  "Message": "Thành công!",
  "StatusCode": 200,
  "ItemsCount": 1,
  "Data": true
}

```

sau call trên thì mất account 899e1ac4-ac26-4207-b49f-167c7862f3d1 trong http://api.easywebhub.com/api-user/GetListUser
api http://api.easywebhub.com/api-user/UpdateUser hình như là DeleteUser

**Comment by thinnv** [comment]
CreateWebsite
https://gist.github.com/thinnv/fc5d284fec5a86b74932266c7c386951

**Comment by baotnq** [comment]
@thinnv  review lại lỗi trong api `UpdateUser` bên trên nghe.

**Comment by thinnv** [comment]
Đã Review nha a Bảo, lý do a Phương push thiếu username, 
Để e đọc thêm tài liệu nói về vụ này của Couchbase

**Comment by nemesisqp** [comment]
- Hàm logon trong websites trả thêm full website info luôn nha @thinnv tại có website id thì cũng không có api nào lấy full info cả, logon không có full site data thì lúc muốn add git url cho site cũng không thể sài ké hàm UpdateUser để ghi đè nguyên array websites của user, nếu được thêm luôn hàm update data của 1 website của 1 user là tiện nhất.
  - API:  http://api.easywebhub.com//api-user/logon
  - Result
  
  ``` json
  {
  "Result": true,
  "Message": "Thành công!",
  "StatusCode": 200,
  "ItemsCount": 1,
  "Data": {
    "AccountId": "752cb8f9-2904-4b4b-98b0-82f335a866b7",
    "AccountType": "user",
    "UserName": "aaa",
    "Password": "qtL63NuENnTjV6R40j+sgV+Utd/5Y9AyZQZ9ftIpt0g=",
    "PasswordSalt": "Ozk1N7Veow3gvwaCWVZK+0unnXH0j4YV",
    "Status": null,
    "Info": null,
    "Websites": [
      {
        "Id": "4be9d95c-8567-4185-9814-3c9bc62cfd4e",
        "DisplayName": "Website of 3"
      }
    ]
  }
  }
  ```
- @baotnq git url của site hiện tại nhiều chỗ quá hiện tại chỉ có 1 git url thì update vô chỗ nào ?

``` json
{
  "stagging": [
        {
          "name": "Github Environment",
          "hostingFee": "free",
          "url": "https://easywebhub.github.io/easy-websites",
          "git": "https://github.com/easywebhub/easy-websites.git"
        }
      ],
      "production": [
        {
          "name": "Github Environment",
          "hostingFee": "free",
          "url": "https://easywebhub.github.io/easy-websites",
          "git": "https://github.com/easywebhub/easy-websites.git"
        },
        {
          "name": "EasyWeb Environment",
          "hosting-fee": "basic",
          "url": "https://easy-web.easywebhub.com",
          "git": "https://git.easywebhub.com/easy-websites.git"
        }
      ]
}
```

**Comment by baotnq** [comment]
@thinnv  em xem lại mô tả của anh để output Json cho đúng nghe.
@nemesisqp : hiện tại sử dụng `"production"` cho `Sync` and `Deploy`, nhưng khác `branch`
    + "production" chỉ chứa 1 đối tượng
    + "stagging" giống y như "production"

@thinnv  lưu ý luôn vấn đề này.

**Comment by baotnq** [comment]
##

- aa

- `bb`
