### ISSUE TITLE
Push to deploy for branch publicAPI

### ISSUE THREAD

**Issue by baotnq** [easywebhub/BackendEasyWeb#4]
- Review update [Readme](https://github.com/easywebhub/BackendEasyWeb/blob/master/README.md#1-api-back-end-net-mvc5-web-api--using-couchbase-nosql-and-rmdb-such-as-mssql-or-mysql)
- Update the push to deploy to xxx.14.140, change branch `gh-pages` to `publicAPI`
- Point to IIS website `api.easywebhub.com` to deployed folder

**Comment by baotnq** [comment]
@tungptvn  thực hiện nghe, @thinnv nắm thông tin

**Comment by baotnq** [comment]
@tungptvn  cái này tới đâu rồi em

**Comment by tungptvn** [comment]
done
![image](https://cloud.githubusercontent.com/assets/11553588/18605266/3b971254-7cb7-11e6-9dfb-db7a730e0977.png)

**Comment by baotnq** [comment]
Test OK with `Public API` branch, view http://api.easywebhub.com/ to see changes on displayed text

Great done! @tungptvn @thinnv .

Should delete Source folder on `push to deploy` branch, remember to do for other repositories
